name: Continuous Integration - MongoDB Controller

on:
  push:
    paths:
      - ".github/workflows/ci-mongodb-controller.yml"
      - "packages/mongodb-controller/**"
  pull_request:
    paths:
      - ".github/workflows/ci-mongodb-controller.yml"
      - "packages/mongodb-controller/**"
    
jobs:
  linter:
    name: Lint Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm --filter "./packages/mongodb-controller" run lint

  test:
    name: Test
    needs: linter
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [20, 22]
        os: [ubuntu-latest]
        mongodb: ['6.0', '7.0']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-replica-set: rs0
          mongodb-version: ${{ matrix.mongodb }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build @kakang/unit
        run: pnpm --filter "./packages/unit" run build

      - name: Build @kakang/eventemitter
        run: pnpm --filter "./packages/eventemitter" run build

      - name: Build @kakang/validator
        run: pnpm --filter "./packages/validator" run build

      - name: Run tests
        run: pnpm --filter "./packages/mongodb-controller" run test
